vlog -work work C:/Users/hasib/OneDrive/Documents/COE328 - Quartus/simulation/modelsim/Lab6Part1Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.decode_vlg_vec_tst
onerror {resume}
add wave {decode_vlg_vec_tst/i1/A}
add wave {decode_vlg_vec_tst/i1/A[7]}
add wave {decode_vlg_vec_tst/i1/A[6]}
add wave {decode_vlg_vec_tst/i1/A[5]}
add wave {decode_vlg_vec_tst/i1/A[4]}
add wave {decode_vlg_vec_tst/i1/A[3]}
add wave {decode_vlg_vec_tst/i1/A[2]}
add wave {decode_vlg_vec_tst/i1/A[1]}
add wave {decode_vlg_vec_tst/i1/A[0]}
add wave {decode_vlg_vec_tst/i1/B}
add wave {decode_vlg_vec_tst/i1/B[7]}
add wave {decode_vlg_vec_tst/i1/B[6]}
add wave {decode_vlg_vec_tst/i1/B[5]}
add wave {decode_vlg_vec_tst/i1/B[4]}
add wave {decode_vlg_vec_tst/i1/B[3]}
add wave {decode_vlg_vec_tst/i1/B[2]}
add wave {decode_vlg_vec_tst/i1/B[1]}
add wave {decode_vlg_vec_tst/i1/B[0]}
add wave {decode_vlg_vec_tst/i1/ATEST}
add wave {decode_vlg_vec_tst/i1/ATEST[7]}
add wave {decode_vlg_vec_tst/i1/ATEST[6]}
add wave {decode_vlg_vec_tst/i1/ATEST[5]}
add wave {decode_vlg_vec_tst/i1/ATEST[4]}
add wave {decode_vlg_vec_tst/i1/ATEST[3]}
add wave {decode_vlg_vec_tst/i1/ATEST[2]}
add wave {decode_vlg_vec_tst/i1/ATEST[1]}
add wave {decode_vlg_vec_tst/i1/ATEST[0]}
add wave {decode_vlg_vec_tst/i1/BTEST}
add wave {decode_vlg_vec_tst/i1/BTEST[7]}
add wave {decode_vlg_vec_tst/i1/BTEST[6]}
add wave {decode_vlg_vec_tst/i1/BTEST[5]}
add wave {decode_vlg_vec_tst/i1/BTEST[4]}
add wave {decode_vlg_vec_tst/i1/BTEST[3]}
add wave {decode_vlg_vec_tst/i1/BTEST[2]}
add wave {decode_vlg_vec_tst/i1/BTEST[1]}
add wave {decode_vlg_vec_tst/i1/BTEST[0]}
add wave {decode_vlg_vec_tst/i1/Clock}
add wave {decode_vlg_vec_tst/i1/data_in}
add wave {decode_vlg_vec_tst/i1/DEC_Enable}
add wave {decode_vlg_vec_tst/i1/DECTEST}
add wave {decode_vlg_vec_tst/i1/DECTEST[15]}
add wave {decode_vlg_vec_tst/i1/DECTEST[14]}
add wave {decode_vlg_vec_tst/i1/DECTEST[13]}
add wave {decode_vlg_vec_tst/i1/DECTEST[12]}
add wave {decode_vlg_vec_tst/i1/DECTEST[11]}
add wave {decode_vlg_vec_tst/i1/DECTEST[10]}
add wave {decode_vlg_vec_tst/i1/DECTEST[9]}
add wave {decode_vlg_vec_tst/i1/DECTEST[8]}
add wave {decode_vlg_vec_tst/i1/DECTEST[7]}
add wave {decode_vlg_vec_tst/i1/DECTEST[6]}
add wave {decode_vlg_vec_tst/i1/DECTEST[5]}
add wave {decode_vlg_vec_tst/i1/DECTEST[4]}
add wave {decode_vlg_vec_tst/i1/DECTEST[3]}
add wave {decode_vlg_vec_tst/i1/DECTEST[2]}
add wave {decode_vlg_vec_tst/i1/DECTEST[1]}
add wave {decode_vlg_vec_tst/i1/DECTEST[0]}
add wave {decode_vlg_vec_tst/i1/firstfourbits}
add wave {decode_vlg_vec_tst/i1/firstfourbits[6]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[5]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[4]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[3]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[2]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[1]}
add wave {decode_vlg_vec_tst/i1/firstfourbits[0]}
add wave {decode_vlg_vec_tst/i1/FMS_reset}
add wave {decode_vlg_vec_tst/i1/lastfourbits}
add wave {decode_vlg_vec_tst/i1/lastfourbits[6]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[5]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[4]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[3]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[2]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[1]}
add wave {decode_vlg_vec_tst/i1/lastfourbits[0]}
add wave {decode_vlg_vec_tst/i1/Reset_A}
add wave {decode_vlg_vec_tst/i1/Reset_B}
add wave {decode_vlg_vec_tst/i1/sign}
add wave {decode_vlg_vec_tst/i1/sign[6]}
add wave {decode_vlg_vec_tst/i1/sign[5]}
add wave {decode_vlg_vec_tst/i1/sign[4]}
add wave {decode_vlg_vec_tst/i1/sign[3]}
add wave {decode_vlg_vec_tst/i1/sign[2]}
add wave {decode_vlg_vec_tst/i1/sign[1]}
add wave {decode_vlg_vec_tst/i1/sign[0]}
add wave {decode_vlg_vec_tst/i1/TESTNUM1}
add wave {decode_vlg_vec_tst/i1/TESTNUM1[3]}
add wave {decode_vlg_vec_tst/i1/TESTNUM1[2]}
add wave {decode_vlg_vec_tst/i1/TESTNUM1[1]}
add wave {decode_vlg_vec_tst/i1/TESTNUM1[0]}
add wave {decode_vlg_vec_tst/i1/TESTNUM2}
add wave {decode_vlg_vec_tst/i1/TESTNUM2[3]}
add wave {decode_vlg_vec_tst/i1/TESTNUM2[2]}
add wave {decode_vlg_vec_tst/i1/TESTNUM2[1]}
add wave {decode_vlg_vec_tst/i1/TESTNUM2[0]}
run -all
